version: '3.3'
services:
  db:
    image: postgres:13.0-alpine
    restart: always
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    env_file:
      - ./.env
      
  # redis:
  #   image: redis:5.0-alpine
  #   ports:
  #     - "6379:6379"

      
volumes:
  postgres_data:
